Validacao/Models/DbContextAp.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Validacao.Models
{
    public class DbContextAp : DbContext
    {
        public DbSet<Jogador> Jogadores { get; set; }
    }
}

Validacao/Models/Jogador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Validacao.Models
{
    public class Jogador
    {
        [HiddenInput(DisplayValue = false)]
        public int JogadorId { get; set; }
        
        [Required (ErrorMessage = "O nome é Obrigatorio")]
        public string Nome { get; set; }
        [Required(ErrorMessage = "O número do Jogador é obrigatorio!")]
        [Range(1,99,ErrorMessage = "O numero do Jogador deve ser maior que 0 e menor que 100")]
        public int ? Numero { get; set; }
        [Required(ErrorMessage = "A altura do Jogador é obrigatoria")]
        [Range(0,double.MaxValue,ErrorMessage = "Digite uma altura valida!")]
        public double ? Altura { get; set; }
    }
}

Validacao/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Validacao.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

Validacao/Controllers/JogadorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Validacao.Models;

namespace Validacao.Controllers
{
    public class JogadorController : Controller
    {
        //
        // GET: /Jogador/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Lista()
        {
            DbContextAp ctx = new DbContextAp();
            return View(ctx.Jogadores);
        }
        [HttpGet]
        public ActionResult Cadastra()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Cadastra(Jogador j)
        {
            //if (String.IsNullOrEmpty(j.Nome))
            //{
            //    ModelState.AddModelError("O nome", "O nome do Jogador é obrigatorio!");
            //}
            //if (j.Numero == null || j.Numero <=0 || j.Numero>=100)
            //{
            //    ModelState.AddModelError("Numero","O numero do jogador dever ser maior que 0 e menor que 100");
            //}
            //if (j.Altura == null || j.Altura == 0)
            //{
            //    ModelState.AddModelError("Altura","Digite uma altura valida!");
            //}
            if (ModelState.IsValid)
            {
                DbContextAp ctx = new DbContextAp();
                ctx.Jogadores.Add(j);
                ctx.SaveChanges();
                return RedirectToAction("Lista");
            }
            else
            {
                return View("Cadastra",j);
            }
            
        }
    }
}

Validacao/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Validacao/Views/Jogador/Cadastra.cshtml
@model Validacao.Models.Jogador

@{
    ViewBag.Title = "Cadastra";
}

<h2>Cadastra</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Jogador</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Numero)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Numero)
            @Html.ValidationMessageFor(model => model.Numero)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Altura)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Altura)
            @Html.ValidationMessageFor(model => model.Altura)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Validacao/Views/Jogador/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

Validacao/Views/Jogador/Lista.cshtml
@using Validacao.Models
@model IEnumerable<Jogador>

@{
    ViewBag.Title = "Lista";
}

<h2>Lista</h2>

<p>
    
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(m => m.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Numero)
        </th>
        <th>
            @Html.DisplayNameFor(m => m.Altura)
        </th>
        <th></th>
    </tr>

@foreach (var jogador in Model) {
    <tr>
        <td>
            @Html.DisplayFor(m => jogador.Nome)
        </td>
        <td>
            @Html.DisplayFor(m => jogador.Numero)
        </td>
        <td>
            @Html.DisplayFor(m => jogador.Altura)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=jogador.JogadorId }) |
            @Html.ActionLink("Details", "Details", new { id=jogador.JogadorId }) |
            @Html.ActionLink("Delete", "Delete", new { id=jogador.JogadorId })
        </td>
    </tr>
}

</table>

Validacao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    @RenderBody()
<div class="ui-menu">
    <div class="ui-menu-item">
        @Html.ActionLink("Lista","Lista","Jogador")
        @Html.ActionLink("Novo","Cadastra","Jogador")
    </div>
</div>

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>